 # $$Numpy基础$$

## 2.1.1 ndarry对象
Numpy提供的同质多维数组可以进行科学运算

In [8]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1, 2],[3, 4]])
c = np.array([1, 2, 3, 4, 5], ndmin = 2) # 规定最小维数
d = np.array([1, 2, 3], dtype=complex)  # 规定数组元素的类型
print(f"a:\n{a}")
print(f"b:\n{b}")
print(f"c:\n{c}")
print(f"d:\n{d}")

a:
[1 2 3]
b:
[[1 2]
 [3 4]]
c:
[[1 2 3 4 5]]
d:
[1.+0.j 2.+0.j 3.+0.j]


### ndarray对象的属性

In [15]:
# 转置
print(f"a的转置:\n{a.T}")
print(f"b的转置:\n{b.T}")
print(f"c的转置:\n{c.T}")

a的转置:
[1 2 3]
b的转置:
[[1 3]
 [2 4]]
c的转置:
[[1]
 [2]
 [3]
 [4]
 [5]]


In [14]:
# 数组中元素个数
print(f"a中元素个数:\n{a.size}")
print(f"b中元素个数:\n{b.size}")
print(f"c中元素个数:\n{c.size}")

a中元素个数:
3
b中元素个数:
4
c中元素个数:
5


In [16]:
# 数组的维度
print(f"a数组的维度:\n{a.ndim}")
print(f"b数组的维度:\n{b.ndim}")
print(f"c数组的维度:\n{c.ndim}")

a数组的维度:
1
b数组的维度:
2
c数组的维度:
2


In [18]:
# 数组的形状
print(f"a数组的形状:\n{a.shape}")
print(f"b数组的形状:\n{b.shape}")
print(f"b数组的行数:\n{b.shape[0]}")
print(f"b数组的列数:\n{b.shape[1]}")
print(f"c数组的形状:\n{c.shape}")

a数组的形状:
(3,)
b数组的形状:
(2, 2)
b数组的行数:
2
b数组的列数:
2
c数组的形状:
(1, 5)


## 2.1.2 创建ndarry对象

In [21]:
# zeros
import numpy as np
x = np.zeros(5) # 默认浮点数
y = np.zeros((5,5), dtype=int) # 指定形状和数据类型
print(x)
print(y)

[0. 0. 0. 0. 0.]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [22]:
# ones
x = np.ones(5)
y = np.ones([3, 3], dtype=int)
print(x)
print(y)

[1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [24]:
# diag
x = np.diag([1,1,1])
y = np.diag([1,2,3])
print(x)
print()
print(y)

[[1 0 0]
 [0 1 0]
 [0 0 1]]

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [25]:
# arange(start, stop, step)创建给定间隔内返回均匀间隔值的数组
# start:默认为0;stop:参数决定;step:默认为1,必须给出start.
a = np.arange(10)
b = np.arange(1, 10)
c = np.arange(1, 10, 2)
print(a)
print(b)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [29]:
# linspace() 生成等差数列
a = np.linspace(1,10,1) # 指定的是数量个数
b = np.linspace(1,10,2)
c = np.linspace(1,10,4)
print(a)
print(b)
print(c)

[1.]
[ 1. 10.]
[ 1.  4.  7. 10.]


In [31]:
# logspace() 生成等比数列
# numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
# 生成10的0次方到10的2次方的数列，共5个数
a = np.logspace(0,2,5)
print(a)
# 生成10的0次方到2的2次方的数列，共3个数
b = np.logspace(0,2,3,base=2)
print(b)


[  1.           3.16227766  10.          31.6227766  100.        ]
[1. 2. 4.]


## 2.1.3 数组变换

### 维度变换


In [40]:
# reshape()更改数组形状
import numpy as np  
# 创建一维数组  
a = np.array([1, 2, 3, 4, 5, 6])  
# 使用 reshape() 方法将一维数组重塑为一个形状为 (2, 3) 的二维数组  
b = a.reshape(2, 3)  
c = a.reshape(2, 3)  # 等价于 b  
# 打印原始数组以及重塑后的数组  
print("原始数组 a:")  
print(a)  
print("\n重塑后的数组 b:")  
print(b)  
print("\n重塑后的数组 c:")  
print(c)

原始数组 a:
[1 2 3 4 5 6]

重塑后的数组 b:
[[1 2 3]
 [4 5 6]]

重塑后的数组 c:
[[1 2 3]
 [4 5 6]]


In [41]:
# flatten() 对数组进行降维，返回一维数组，原数组不变
# 创建一个 2x3 的二维数组  
arr = np.array([[1, 2, 3],  
                [4, 5, 6]])  
# 使用 flatten()  
flat_arr = arr.flatten()  
print("Original array:\n", arr)  
print("After flatten():", flat_arr) 
print() 
# 使用 ravel()  
raveled_arr = arr.ravel()  
print("After ravel():", raveled_arr)
print()
# 使用 reshape(-1)  
reshaped_arr = arr.reshape(-1)  
print("After reshape(-1):", reshaped_arr)

Original array:
 [[1 2 3]
 [4 5 6]]
After flatten(): [1 2 3 4 5 6]

After ravel(): [1 2 3 4 5 6]

After reshape(-1): [1 2 3 4 5 6]


### 数组拼接

In [42]:
import numpy as np  

# 创建两个二维数组  
arr1 = np.array([[1, 2],  
                 [3, 4]])  
arr2 = np.array([[5, 6],  
                 [7, 8]])  

print("arr1结果:\n", arr1)
print("arr2结果:\n", arr2)

# 使用 hstack()  沿水平方向(列的方向)拼接数组
hstacked = np.hstack((arr1, arr2))  
print("hstack结果:\n", hstacked)

# 使用 vstack()  沿垂直方向(行的方向)拼接数组
vstacked = np.vstack((arr1, arr2))  
print("vstack结果:\n", vstacked)

# concatenate()沿指定轴拼接数组.需要指定轴的参数(axis),axis 指定拼接的轴(0 表示行,1 表示列).
# 使用 concatenate() 沿列拼接(axis=1)  
concatenated_h = np.concatenate((arr1, arr2), axis=1)  
print("沿列拼接的结果:\n", concatenated_h)  

# 使用 concatenate() 沿行拼接(axis=0)  
concatenated_v = np.concatenate((arr1, arr2), axis=0)  
print("沿行拼接的结果:\n", concatenated_v)

arr1结果:
 [[1 2]
 [3 4]]
arr2结果:
 [[5 6]
 [7 8]]
hstack结果:
 [[1 2 5 6]
 [3 4 7 8]]
vstack结果:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
沿列拼接的结果:
 [[1 2 5 6]
 [3 4 7 8]]
沿行拼接的结果:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


### 数组分割

In [ ]:
import numpy as np  

# 创建一个 2x6 的二维数组  
arr = np.array([[1, 2, 3, 4, 5, 6],  
                [7, 8, 9, 10, 11, 12]])  

# 使用 hsplit() 将数组分成 3 份  
hsplit_result = np.hsplit(arr, 3)  
print("hsplit结果:")  
for i, part in enumerate(hsplit_result):  
    print(f"部分 {i + 1}:\n", part)

# 使用 vsplit() 将数组分成 2 份  
vsplit_result = np.vsplit(arr, 2)  
print("vsplit结果:")  
for i, part in enumerate(vsplit_result):  
    print(f"部分 {i + 1}:\n", part)

# 使用 split() 沿列( axis=1 )分割数组  
split_result_horizontal = np.split(arr, 3, axis=1)  
print("沿列分割的结果:")  
for i, part in enumerate(split_result_horizontal):  
    print(f"部分 {i + 1}:\n", part)  

# 使用 split() 沿行( axis=0 )分割数组  
split_result_vertical = np.split(arr, 2, axis=0)  
print("沿行分割的结果:")  
for i, part in enumerate(split_result_vertical):  
    print(f"部分 {i + 1}:\n", part)

hsplit结果:
部分 1:
 [[1 2]
 [7 8]]
部分 2:
 [[ 3  4]
 [ 9 10]]
部分 3:
 [[ 5  6]
 [11 12]]
vsplit结果:
部分 1:
 [[1 2 3 4 5 6]]
部分 2:
 [[ 7  8  9 10 11 12]]
沿列分割的结果:
部分 1:
 [[1 2]
 [7 8]]
部分 2:
 [[ 3  4]
 [ 9 10]]
部分 3:
 [[ 5  6]
 [11 12]]
沿行分割的结果:
部分 1:
 [[1 2 3 4 5 6]]
部分 2:
 [[ 7  8  9 10 11 12]]


### 数组复制

In [46]:
import numpy as np  
# 创建一个数组  
arr1 = np.array([1, 2, 3, 4, 5])  
# 使用 copy() 进行数组复制,不改变原数组 
arr_copy_1 = arr1.copy()  
# 修改原数组  
arr1[0] = 10  
print("原数组 arr1:", arr1)  
print("复制的数组 arr_copy:", arr_copy_1)
print()
# 使用 [:]进行数组复制,改变原数组 
arr_copy_2 = arr1[:]  
# 修改原数组  
arr1[0] = 10  
print("原数组 arr1:", arr1)  
print("复制的数组 arr_copy:", arr_copy_2)

原数组 arr1: [10  2  3  4  5]
复制的数组 arr_copy: [1 2 3 4 5]

原数组 arr1: [10  2  3  4  5]
复制的数组 arr_copy: [10  2  3  4  5]


### 数组索引

#### 一维数组索引

In [47]:
import numpy as np  

# 创建一维数组  
arr1d = np.array([10, 20, 30, 40, 50])  

# 基本索引  
print("索引 0:", arr1d[0])  # 第一个元素  
print("索引 2:", arr1d[2])  # 第三元素  

# 切片  
print("切片 [1:4]:", arr1d[1:4])  # 从索引 1 到 3（不包括 4）  
print("切片 [:3]:", arr1d[:3])      # 取前三个元素  
print("切片 [2:]:", arr1d[2:])      # 从索引 2 到结尾  
print("切片 [::2]:", arr1d[::2])    # 每隔一个取一个元素

索引 0: 10
索引 2: 30
切片 [1:4]: [20 30 40]
切片 [:3]: [10 20 30]
切片 [2:]: [30 40 50]
切片 [::2]: [10 30 50]


#### 二维数组的索引和切片

In [48]:
# 创建二维数组  
arr2d = np.array([[1, 2, 3],  
                  [4, 5, 6],  
                  [7, 8, 9]])  

# 基本索引  
print("索引 (1, 1):", arr2d[1, 1])  # 访问第二行第二列元素  
print("索引 (2, 0):", arr2d[2, 0])  # 访问第三行第一列元素  

# 行切片  
print("行切片 [0:2]:\n", arr2d[0:2])      # 取前两行  
print("行切片 [:2]:\n", arr2d[:2])         # 取前两行  
print("行切片 [::2]:\n", arr2d[::2])       # 每隔一行取一行  

# 列切片  
print("列切片 [:, 1]:", arr2d[:, 1])     # 取第二列  
print("部分切片 [1:, 0:2]:\n", arr2d[1:, 0:2])  # 取第二行及以后，前两列

索引 (1, 1): 5
索引 (2, 0): 7
行切片 [0:2]:
 [[1 2 3]
 [4 5 6]]
行切片 [:2]:
 [[1 2 3]
 [4 5 6]]
行切片 [::2]:
 [[1 2 3]
 [7 8 9]]
列切片 [:, 1]: [2 5 8]
部分切片 [1:, 0:2]:
 [[4 5]
 [7 8]]


#### 布尔索引

In [49]:
# 创建一维数组  
arr = np.array([10, 20, 30, 40, 50])  

# 使用布尔索引  
bool_idx = arr > 30  # 创建布尔索引，条件为大于 30  
print("满足条件的元素:", arr[bool_idx])  # 选择所有大于 30 的元素

满足条件的元素: [40 50]


## 2.1.4 生成随机数

### 生成均匀分布的随机数

In [55]:
import numpy as np  

# 生成单个随机数  
random_number = np.random.rand()  # 生成0到1之间的随机浮点数  
print("单个均匀分布随机数:", random_number)  

# 生成一定形状的均匀分布随机数组  
random_array = np.random.rand(3, 4)  # 生成3行4列的随机数组  
print("均匀分布随机数组:\n", random_array)

单个均匀分布随机数: 0.9209140208518813
均匀分布随机数组:
 [[0.02472827 0.67532689 0.52610444 0.99064024]
 [0.93466715 0.42275341 0.33204757 0.89922078]
 [0.23559347 0.84452078 0.67347522 0.03653894]]


### 生成正态分布随机数

In [57]:
# 生成符合标准正态分布（均值0，标准差1）的随机数  
normal_random = np.random.randn(2, 3)  # 生成2行3列的随机数组  
print("正态分布随机数组:\n", normal_random)  

# 生成指定均值和标准差的正态分布随机数  
mean = 5  
std_dev = 2  
normal_custom = np.random.normal(mean, std_dev, (2, 3))  # 生成2行3列的随机数组  
print("指定均值和标准差的正态分布随机数组:\n", normal_custom)
np.random.randn()

正态分布随机数组:
 [[-0.85170294  0.20555247 -1.07585454]
 [ 0.74060754 -0.12835789 -0.66039251]]
指定均值和标准差的正态分布随机数组:
 [[7.82706431 8.21855246 7.97172893]
 [5.93812609 3.80074683 7.70520495]]


-1.7094139159254536

### 生成整数随机数


In [58]:
# 生成从low到high之间的随机整数  
random_int = np.random.randint(1, 10, size=(3, 4))  # 生成3行4列的随机整数  
print("随机整数数组:\n", random_int)

随机整数数组:
 [[9 9 2 7]
 [4 3 3 4]
 [8 8 3 7]]


In [64]:
random_int_range = np.random.randint(1, 10, size=5)  # 生成5个在1到10之间的随机整数  
print("随机整数数组:", random_int_range)

随机整数数组: [8 5 4 8 8]


### 从离散分布中抽样

In [59]:
# 将事件及其对应的概率放入列表中  
values = [1, 2, 3, 4, 5]  
probabilities = [0.1, 0.2, 0.3, 0.2, 0.2]  # 概率和为1  

# 从离散分布中抽样  
discrete_sample = np.random.choice(values, size=(3, 4), p=probabilities)  # 生成3行4列的样本  
print("从离散分布中抽样结果:\n", discrete_sample)

从离散分布中抽样结果:
 [[5 5 3 4]
 [3 3 3 4]
 [4 5 5 5]]


### 生成随机排列

In [60]:
# 创建一个数组并生成随机排列  
original_array = np.array([1, 2, 3, 4, 5])  
shuffled_array = np.random.permutation(original_array)  # 随机排列数组  
print("随机排列后的数组:", shuffled_array)

随机排列后的数组: [4 3 5 2 1]


### 生成布尔随机数

In [61]:
# 生成布尔随机数组  
random_bool = np.random.choice([True, False], size=(3, 4))  # 生成3行4列的布尔数组  
print("布尔随机数组:\n", random_bool)

布尔随机数组:
 [[False  True False  True]
 [False False False  True]
 [ True False False False]]


### 设定随机种子

In [63]:
# 设定随机种子  
np.random.seed(42)  

# 生成随机数  
seeded_random = np.random.rand(2, 3)  
print("设定随机种子的随机数:\n", seeded_random)
np.random.rand() 

设定随机种子的随机数:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]


0.05808361216819946