# $$线性代数与统计量$$

# 线性代数

In [ ]:
import numpy as np  

# 创建2x3的矩阵  
A = np.array([[1, 2, 3],  
              [4, 5, 6]])  

# 创建3x2的矩阵  
B = np.array([[7, 8],  
              [9, 10],  
              [11, 12]])  

print("矩阵 A:\n", A)  
print("矩阵 B:\n", B)


矩阵 A:
 [[1 2 3]
 [4 5 6]]
矩阵 B:
 [[ 7  8]
 [ 9 10]
 [11 12]]


## 矩阵运算

In [3]:
# 创建两个相同形状的矩阵  
C = np.array([[1, 1, 1],  
              [1, 1, 1]])  

# 矩阵加法  
D = A + C  
print("矩阵 A + 矩阵 C:\n", D)

# 矩阵乘法 (A 和 B 的乘积)  
product = np.dot(A, B)  # 或者使用 A @ B  
print("矩阵 A 和 B 的乘积：\n", product)

# 矩阵转置  
A_transpose = A.T  
print("矩阵 A 的转置：\n", A_transpose)


矩阵 A + 矩阵 C:
 [[2 3 4]
 [5 6 7]]
矩阵 A 和 B 的乘积：
 [[ 58  64]
 [139 154]]
矩阵 A 的转置：
 [[1 4]
 [2 5]
 [3 6]]


## 行列式

In [5]:
# 创建一个方阵  
square_matrix = np.array([[1, 2],  
                          [3, 4]])  

det = np.linalg.det(square_matrix)  
print("方阵的行列式:", det)

# 计算逆矩阵  
inv_matrix = np.linalg.inv(square_matrix)  
print("方阵的逆矩阵：\n", inv_matrix)

# 设定方程组 Ax = b  
A_eq = np.array([[3, 1],   
                 [1, 2]])  
b_eq = np.array([9, 8])  

# 求解方程  
solution = np.linalg.solve(A_eq, b_eq)  
print("线性方程组的解：", solution)

# 计算特征值和特征向量  
eigenvalues, eigenvectors = np.linalg.eig(square_matrix)  
print("特征值:", eigenvalues)  
print("特征向量：\n", eigenvectors)

# 奇异值分解  
U, S, Vt = np.linalg.svd(A)  
print("U矩阵：\n", U)  
print("奇异值：", S)  
print("Vt矩阵：\n", Vt)



方阵的行列式: -2.0000000000000004
方阵的逆矩阵：
 [[-2.   1. ]
 [ 1.5 -0.5]]
线性方程组的解： [2. 3.]
特征值: [-0.37228132  5.37228132]
特征向量：
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
U矩阵：
 [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]
奇异值： [9.508032   0.77286964]
Vt矩阵：
 [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]


# 统计量

## 一维数组

In [6]:
import numpy as np  

# 创建一维数组  
data_1d = np.array([10, 20, 30, 40, 50])  

# 计算平均值  
mean_1d = np.mean(data_1d)  
print("一维数组平均值:", mean_1d)  

# 计算中位数  
median_1d = np.median(data_1d)  
print("一维数组中位数:", median_1d)  

# 计算标准差  
std_1d = np.std(data_1d)  
print("一维数组标准差:", std_1d)  

# 计算方差  
var_1d = np.var(data_1d)  
print("一维数组方差:", var_1d)  

# 计算最大值和最小值  
max_1d = np.max(data_1d)  
min_1d = np.min(data_1d)  
print("一维数组最大值:", max_1d, "最小值:", min_1d)  

# 计算四分位数  
q1_1d = np.percentile(data_1d, 25)  
q3_1d = np.percentile(data_1d, 75)  
print("一维数组第一四分位数:", q1_1d, "第三四分位数:", q3_1d)

一维数组平均值: 30.0
一维数组中位数: 30.0
一维数组标准差: 14.142135623730951
一维数组方差: 200.0
一维数组最大值: 50 最小值: 10
一维数组第一四分位数: 20.0 第三四分位数: 40.0


## 多维数组

In [7]:
# 创建二维数组（矩阵）  
data_2d = np.array([[10, 20, 30],  
                    [40, 50, 60],  
                    [70, 80, 90]])  

# 计算按列的平均值  
mean_2d_col = np.mean(data_2d, axis=0)  # 按列计算  
print("二维数组按列的平均值:", mean_2d_col)  

# 计算按行的中位数  
median_2d_row = np.median(data_2d, axis=1)  # 按行计算  
print("二维数组按行的中位数:", median_2d_row)  

# 计算按列的标准差  
std_2d_col = np.std(data_2d, axis=0)  
print("二维数组按列的标准差:", std_2d_col)  

# 计算按行的方差  
var_2d_row = np.var(data_2d, axis=1)  
print("二维数组按行的方差:", var_2d_row)  

# 计算最大值和最小值（按列和按行）  
max_2d_col = np.max(data_2d, axis=0)  # 每列的最大值  
min_2d_row = np.min(data_2d, axis=1)  # 每行的最小值  
print("二维数组每列的最大值:", max_2d_col)  
print("二维数组每行的最小值:", min_2d_row)  

# 计算四分位数（按列计算）  
q1_2d_col = np.percentile(data_2d, 25, axis=0)  
q3_2d_col = np.percentile(data_2d, 75, axis=0)  
print("二维数组按列的第一四分位数:", q1_2d_col, "第三四分位数:", q3_2d_col)

# 创建一个二维数组  
data_2d = np.array([[1, 2, 3],  
                    [4, 5, 6]])  

covariance_matrix = np.cov(data_2d, rowvar=False)  
correlation_matrix = np.corrcoef(data_2d)  

print("协方差矩阵：\n", covariance_matrix)  
print("相关系数矩阵：\n", correlation_matrix) 



二维数组按列的平均值: [40. 50. 60.]
二维数组按行的中位数: [20. 50. 80.]
二维数组按列的标准差: [24.49489743 24.49489743 24.49489743]
二维数组按行的方差: [66.66666667 66.66666667 66.66666667]
二维数组每列的最大值: [70 80 90]
二维数组每行的最小值: [10 40 70]
二维数组按列的第一四分位数: [25. 35. 45.] 第三四分位数: [55. 65. 75.]
协方差矩阵：
 [[4.5 4.5 4.5]
 [4.5 4.5 4.5]
 [4.5 4.5 4.5]]
相关系数矩阵：
 [[1. 1.]
 [1. 1.]]


## 求和

In [8]:
import numpy as np  

# 创建一维数组  
data_1d = np.array([1, 2, 3, 4, 5])  
sum_1d = np.sum(data_1d)  
print("一维数组求和:", sum_1d)  # 输出 15

# 创建二维数组  
data_2d = np.array([[1, 2, 3],  
                    [4, 5, 6],  
                    [7, 8, 9]])  

# 按行求和  
sum_rows = np.sum(data_2d, axis=1)  # 按行求和  
print("二维数组按行求和:", sum_rows)  # 输出 [  6  15  24]  

# 按列求和  
sum_columns = np.sum(data_2d, axis=0)  # 按列求和  
print("二维数组按列求和:", sum_columns)  # 输出 [12 15 18]



一维数组求和: 15
二维数组按行求和: [ 6 15 24]
二维数组按列求和: [12 15 18]


## 皮尔逊相关系数


1. 皮尔逊相关系数的值的范围在 -1 到 1 之间：

- 1：表示完全正相关（两个变量一起增加）。
- 0：表示没有线性相关关系（一个变量的变化与另一个变量无关）。
- -1：表示完全负相关（一个变量增加时另一个变量减少）

2. 评价标准：
- 0.9 到 1.0 (或 -0.9 到 -1.0)：强正（或负）相关
- 0.7 到 0.9 (或 -0.7 到 -0.9)：中等正（或负）相关
- 0.3 到 0.7 (或 -0.3 到 -0.7)：弱正（或负）相关
- 0 到 0.3 (或 0 到 -0.3)：无相关性

In [9]:
# 创建二维数组，假设每行是一个样本，每列是一个特征  
data_2d = np.array([[1, 2, 3],  
                    [4, 5, 6],  
                    [7, 8, 9]])  

# 计算皮尔逊相关系数矩阵  
correlation_matrix = np.corrcoef(data_2d, rowvar=False)  
print("皮尔逊相关系数矩阵：\n", correlation_matrix)

皮尔逊相关系数矩阵：
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
import numpy as np  

# 创建两个二维数组(矩阵)  
data1 = np.array([[1, 2, 3],  
                  [4, 5, 6],  
                  [7, 8, 9]])  

data2 = np.array([[9, 8, 7],  
                  [6, 5, 4],  
                  [3, 2, 1]])  

# 计算两个矩阵的皮尔逊相关系数  
print("矩阵1:\n",data1)
print("矩阵2:\n",data2)
correlation_matrix = np.corrcoef(data1, data2)
print("皮尔逊相关系数矩阵:\n", correlation_matrix)

矩阵1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
矩阵2:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
皮尔逊相关系数矩阵:
 [[ 1.  1.  1. -1. -1. -1.]
 [ 1.  1.  1. -1. -1. -1.]
 [ 1.  1.  1. -1. -1. -1.]
 [-1. -1. -1.  1.  1.  1.]
 [-1. -1. -1.  1.  1.  1.]
 [-1. -1. -1.  1.  1.  1.]]
